name: SWF to Unsigned IPA

on:
  workflow_dispatch:
    inputs:
      swf_file:
        description: 'Path to SWF file in repo'
        required: true
        default: 'app.swf'
      app_descriptor:
        description: 'Path to AIR Application Descriptor XML'
        required: true
        default: 'App-app.xml'
      output_name:
        description: 'Name of the generated IPA'
        required: false
        default: 'orange.ipa'

jobs:
  build:
    name: Build Unsigned IPA from SWF
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install AIR SDK Manager and Download SDK
        run: |
             curl -L -o AIRSDKManager.pkg https://github.com/airsdk/airsdkmanager-releases/releases/download/v1.1.2/AIRSDKManager_1.1.2.pkg
             sudo installer -pkg AIRSDKManager.pkg -target /
             /usr/local/bin/sdkmanager install latest --os macos --output airsdk

      - name: Build Unsigned IPA with ADT
        run: |
          ./airsdk/bin/adt \
            -package \
            -target ipa-test \
            ${{ github.event.inputs.output_name }} \
            ${{ github.event.inputs.app_descriptor }} \
            ${{ github.event.inputs.swf_file }}

      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.output_name }}
          path: ${{ github.event.inputs.output_name }}
          retention-days: 90
