name: SWF to Unsigned IPA

on:
  workflow_dispatch:
    inputs:
      swf_file:
        description: 'Path to SWF file in repo'
        required: true
        default: 'app.swf'
      app_descriptor:
        description: 'Path to AIR Application Descriptor XML'
        required: true
        default: 'App-app.xml'
      output_name:
        description: 'Name of the generated IPA'
        required: false
        default: 'orange.ipa'

jobs:
  build:
    name: Build Unsigned IPA from SWF
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download and Extract AIR SDK
        run: |
         echo "Downloading AIR SDK..."
         curl -L -o airsdk.zip "https://airsdk.harman.com/api/versions/51.2.1.5/sdks/AIRSDK_MacOS.zip?license=accepted"
 
         echo "Extracting AIR SDK..."
         mkdir -p airsdk
         unzip -q airsdk.zip -d airsdk


      - name: Build Unsigned IPA with ADT
        run: |
          ./airsdk/bin/adt \
            -package \
            -target ipa-test \
            ${{ github.event.inputs.output_name }} \
            ${{ github.event.inputs.app_descriptor }} \
            ${{ github.event.inputs.swf_file }}

      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.output_name }}
          path: ${{ github.event.inputs.output_name }}
          retention-days: 90
