name: SWF to Unsigned IPA

on:
  workflow_dispatch:
    inputs:
      swf_file:
        description: 'Path to SWF file in repo'
        required: true
        default: 'app.swf'
      app_descriptor:
        description: 'Path to AIR Application Descriptor XML'
        required: true
        default: 'App-app.xml'
      output_name:
        description: 'Name of the generated IPA'
        required: false
        default: 'orange.ipa'

jobs:
  build:
    name: Build Unsigned IPA from SWF
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download and Extract AIR SDK
        run: |
          # Step 1: Download the ZIP archive.
          echo "Downloading AIR SDK..."
          curl -L -o airsdk.zip "https://airsdk.harman.com/api/versions/51.2.1.5/sdks/AIRSDK_MacOS.zip?license=accepted"

          # Step 2: Unzip the archive.
          # The -q flag is removed to show detailed output of all extracted files.
          echo "Extracting AIR SDK..."
          unzip airsdk.zip

          # Step 3: DEBUG - List the contents of the current directory.
          # This will show you the actual name of the directory created by the unzip command.
          echo "Listing contents after unzip:"
          ls -l

          # Step 4: This mv command is now expected to fail, but the ls output above will tell you how to fix it.
          echo "Attempting to standardize SDK directory name..."
          mv AIRSDK* airsdk




      - name: Build Unsigned IPA with ADT
        run: |
          ./airsdk/bin/adt \
            -package \
            -target ipa-test \
            ${{ github.event.inputs.output_name }} \
            ${{ github.event.inputs.app_descriptor }} \
            ${{ github.event.inputs.swf_file }}

      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.output_name }}
          path: ${{ github.event.inputs.output_name }}
          retention-days: 90
